array_width = 60
binop_separator = "Back"
use_field_init_shorthand = true
fn_single_line = true
combine_control_expr = true
wrap_comments = true
imports_indent = "Visual"
tab_spaces = 4
enum_discrim_align_threshold = 20
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
hex_literal_case = "Lower"
match_arm_leading_pipes = "Always"
match_block_trailing_comma = true
imports_granularity = "Module"
newline_style = "unix"
normalize_comments = true
group_imports = "StdExternalCrate"
unstable_features = true
